# Generated by Django 5.1.6 on 2025-03-08 13:10

import noticiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(help_text='Digite uma breve descrição sobre a notícia...', max_length=255)),
                ('capa', models.ImageField(upload_to=noticiais.models.renomear_uploaded_file)),
                ('slug_url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('corpo', models.TextField()),
                ('data', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
