# Generated by Django 5.1.6 on 2025-03-04 12:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_categoria', models.ImageField(upload_to='linkagro_categorias/')),
                ('banner_categoria', models.ImageField(upload_to='linkagro_categorias_banner/')),
                ('nome_categoria', models.CharField(max_length=255, unique=True)),
                ('slug_categoria', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descricao_categoria', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regioes',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='app.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('imagem_produto', models.ImageField(upload_to='linkagro_categorias/produtos/')),
                ('descricao_produto', models.TextField(blank=True, null=True)),
                ('slug_produto', models.SlugField(blank=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('epoca_colheita_produto', models.CharField(blank=True, choices=[('primavera', 'Primavera'), ('outono', 'Outono'), ('anual', 'Anual')], default='Anual', help_text='Exemplo: Primavera, Outono, Anual', max_length=100, null=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_produtos', to='app.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='linkagro_produtores/')),
                ('nome_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('telefone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_produtor', models.CharField(choices=[('individual', 'Individual'), ('entidade', 'Entidade'), ('grupo', 'Grupo'), ('anual', 'Anual')], default='individual', max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor_distrito', to='app.distrito')),
                ('localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor_localidade', to='app.localidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produtor', to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor_provincia', to='app.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='app.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='app.regiao'),
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variedade', models.CharField(max_length=100)),
                ('slug_variedade', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descricao_variedade', models.TextField(blank=True, null=True)),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_variedade', models.PositiveIntegerField(default=0)),
                ('quantidade_variedade', models.PositiveIntegerField(default=0)),
                ('unidade_variedade', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('t', 'Tonelada (t)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('cx', 'Caixa (cx)'), ('sc', 'Saca (sc)'), ('un', 'Unidade (un)')], default='kg', help_text='Escolha a unidade de medida (ex: kg, litro, saca)', max_length=5)),
                ('qualidade', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=20)),
                ('epoca_de_colheita', models.CharField(choices=[('primavera', 'Primavera'), ('verao', 'Verão'), ('outono', 'Outono'), ('inverno', 'Inverno'), ('anual', 'Anual')], default='anual', max_length=10)),
                ('data_inicio_colheita', models.DateField()),
                ('data_fim_colheita', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producao_distrito', to='app.distrito')),
                ('localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producao_localidade', to='app.localidade')),
                ('produto_variedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_variedades', to='app.produto')),
                ('produtor_variedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtor_variedades', to='app.produtor')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producao_provincia', to='app.provincia')),
            ],
            options={
                'verbose_name': 'Variedade',
                'verbose_name_plural': 'Variedades',
                'ordering': ['-data_inicio_colheita', 'nome_variedade'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaVariedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_variedade', models.ImageField(upload_to='linkagro_categorias/produtos/variedade_galeria/')),
                ('default', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('variedade_galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedade_galerias', to='app.variedade')),
            ],
            options={
                'ordering': ['default'],
            },
        ),
        migrations.AddConstraint(
            model_name='variedade',
            constraint=models.UniqueConstraint(fields=('produto_variedade', 'nome_variedade', 'produtor_variedade'), name='unique_variedade_produto'),
        ),
    ]
