# Generated by Django 5.1.6 on 2025-03-04 13:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='banner_categoria',
            field=models.ImageField(upload_to=app.models.renomear_uploaded_categoria_banner),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.ImageField(upload_to=app.models.renomear_uploaded_categoria),
        ),
        migrations.AlterField(
            model_name='galeriavariedade',
            name='imagem_variedade',
            field=models.ImageField(upload_to=app.models.renomear_uploaded_variedade),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(upload_to=app.models.renomear_uploaded_produto),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.renomear_uploaded_file),
        ),
    ]
