# Generated by Django 5.1.6 on 2025-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriavariedade',
            options={'ordering': ['-default']},
        ),
        migrations.AlterField(
            model_name='galeriavariedade',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
