# Generated by Django 5.1.6 on 2025-03-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_galeriavariedade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-variedades_activas'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
