# Generated by Django 5.1.6 on 2025-03-10 01:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='banner_categoria',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_categorias/banner'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagem_categoria',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_categorias'),
        ),
        migrations.AlterField(
            model_name='galeriavariedade',
            name='imagem_variedade',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_categorias/produtos/variedade_galeria/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_categorias/produtos/'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='logotipo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='linkagro_produtor'),
        ),
    ]
