# Generated by Django 5.1.6 on 2025-03-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='Imagem', max_length=10)),
                ('arquivo', models.FileField(upload_to='linkagro_banners/')),
                ('activo', models.BooleanField(default=False)),
                ('mostrar_texto', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='linkagro_parceiros/')),
                ('mostrar_texto', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Armazenista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='linkagro_armazenista/')),
                ('telefone', models.CharField(max_length=20)),
                ('telefone_2', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazenista_distrito', to='app.distrito')),
                ('localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazenista_localidade', to='app.localidade')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazenista_provincia', to='app.provincia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armazenista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Armazenista',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_armazem', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('numero_local_armazem', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('unidade_armazenamento', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('t', 'Tonelada (t)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('cx', 'Caixa (cx)'), ('sc', 'Saca (sc)'), ('un', 'Unidade (un)')], default='kg', help_text='Escolha a unidade de medida (ex: kg, litro, saca)', max_length=5)),
                ('capacidade_maxima', models.PositiveIntegerField(help_text='Capacidade máxima de armazenagem (em unidades)')),
                ('lotacao', models.PositiveIntegerField(help_text='Capacidade máxima de armazenagem (em unidades)')),
                ('condicoes_armazenagem', models.TextField(help_text='Condições específicas para armazenagem de produtos')),
                ('dimensao', models.CharField(help_text='Dimensão do armazém, por exemplo, 10x20m', max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('disponivel', models.BooleanField(default=True, help_text='Se o armazém está disponível para receber novos produtos')),
                ('armazenar_produto', models.ManyToManyField(related_name='produtos_armazenados', to='app.produto')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazem_distrito', to='app.distrito')),
                ('localidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazem_localidade', to='app.localidade')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazem_provincia', to='app.provincia')),
                ('armazenista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazem', to='anuncios.armazenista')),
            ],
            options={
                'verbose_name_plural': 'Armazens',
                'ordering': ['disponivel', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AvaliarArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliar_armazem', models.DecimalField(blank=True, decimal_places=2, help_text='De 1-5', max_digits=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_armazem', models.ImageField(upload_to='linkagro_aramzem_galeria/')),
                ('default', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('armazem_galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazem_galeria', to='anuncios.armazem')),
            ],
        ),
    ]
