# Generated by Django 5.1.6 on 2025-03-10 01:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_banners/'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='linkagro_parceiros/'),
        ),
    ]
